name: 🚀 Deploy React App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Checkout repository (optional but good practice)
        uses: actions/checkout@v4

      - name: 🚀 Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}             # e.g., 160.250.204.205
          username: ${{ secrets.VPS_USER }}         # e.g., root or ubuntu
          key: ${{ secrets.VPS_PRIVATE_KEY }}       # private key from ~/.ssh/id_rsa_cicd
          port: 22
          script: |
           bash ~/deploy-react.sh
                      
